Sithous\AntiSpamBundle\Entity\SithousAntiSpam:
    type: entity
    table: null
    repositoryClass: Sithous\AntiSpamBundle\Entity\SithousAntiSpamRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        ip:
            type: string
            length: 45
            nullable: true
        userObject:
            type: string
            length: 255
            nullable: true
        userId:
            type: integer
            nullable: true
        dateTime:
            type: datetime
    manyToOne:
        type:
            targetEntity: Sithous\AntiSpamBundle\Entity\SithousAntiSpamType
            inversedBy: SithousAntiSpam
            joinColumn:
                name: type_id
                referencedColumnName: id
                onDelete: CASCADE
    lifecycleCallbacks: {  }
